.ifndef TILES_INC
TILES_INC = 1

BLANK          = $000
; 1-8 walls
HBAR           = $009
VBAR           = $00A
HLOCK          = $00B
VLOCK          = $00C
PELLET         = $00D
POWER_PELLET   = $00E
PLAYER_CHAR    = $00F
KEY            = $010
TIMES          = $011
CHERRY         = $012
LOGO1          = $013
LOGO2          = $014
LOGO3          = $015
LOGO4          = $016
LOGO5          = $017
HOME_FENCE     = $018



.endif
