.ifndef TILES_INC
TILES_INC = 1

BLANK          = $000
; 1-9 walls
HBAR           = $00A
VBAR           = $00B
HLOCK          = $00C
VLOCK          = $00D
PELLET         = $00E
POWER_PELLET   = $00F
PLAYER_CHAR    = $010
KEY            = $011
TIMES          = $012
LOGO1          = $013
LOGO2          = $014
LOGO3          = $015
LOGO4          = $016
LOGO5          = $017
HOME_FENCE     = $018
BANANA         = $019
MANGO          = $01A
; $1B-1E "Press START or ENTER to Play"
GUAVA          = $01F
; $20-$5A ASCII characters
; $5B-$D1 Start Screen
GRAPEFRUIT     = $0D2
CARAMBOLA      = $0D3
CHERRY         = $020
APPLE          = $095


.endif
