.ifndef TILES_INC
TILES_INC = 1

BLANK          = $000
; 1-9 walls
HBAR           = $00A
VBAR           = $00B
HLOCK          = $00C
VLOCK          = $00D
PELLET         = $00E
POWER_PELLET   = $00F
PLAYER_CHAR    = $010
KEY            = $011
TIMES          = $012
LOGO1          = $013
LOGO2          = $014
LOGO3          = $015
LOGO4          = $016
LOGO5          = $017
HOME_FENCE     = $018
BANANA         = $019
MANGO          = $01A
GUAVA          = $01F
GRAPEFRUIT     = $0D2
CARAMBOLA      = $0D3
CHERRY         = $0D4
APPLE          = $0D5


.endif
